export const AIRPORTS = [
    {
        code: "CDG",
        lat: "49.0175",
        lon: "2.5564",
        name: "Charles de Gaulle International Airport",
        city: "Le Mesnil-Amelot",
        state: "Ile-de-France",
        country: "France",
        woeid: "22140453",
        tz: "Europe/Paris",
        phone: "",
        type: "Airports",
        email: "",
        url: "",
        runway_length: "11811",
        elev: "387",
        icao: "LFPG",
        direct_flights: "310",
        carriers: "131",
    },
    {
        code: "LAX",
        lat: "33.9456",
        lon: "-118.391",
        name: "Los Angeles International Airport",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        woeid: "12520706",
        tz: "America/Los_Angeles",
        phone: "",
        type: "Airports",
        email: "",
        url: "",
        runway_length: "12091",
        elev: "126",
        icao: "KLAX",
        direct_flights: "200",
        carriers: "99",
    },
    {
        code: "LGW",
        lat: "51.1568",
        lon: "-0.16988",
        name: "London Gatwick Airport",
        city: "Horley",
        state: "England",
        country: "United Kingdom",
        woeid: "23387567",
        tz: "Europe/London",
        phone: "0870 000 2468",
        type: "Airports",
        email: "",
        url: "http://www.gatwickairport.com/",
        runway_length: "10364",
        elev: "202",
        icao: "",
        direct_flights: "227",
        carriers: "71",
    },
    {
        code: "LHR",
        lat: "51.4703",
        lon: "-0.45342",
        name: "London Heathrow Airport",
        city: "Hounslow",
        state: "England",
        country: "United Kingdom",
        woeid: "23382429",
        tz: "Europe/London",
        phone: "+44 (0)8700 000698",
        type: "Airports",
        email: "",
        url: "http://www.heathrowairport.com",
        runway_length: "12802",
        elev: "80",
        icao: "EGLL",
        direct_flights: "227",
        carriers: "105",
    },
    {
        code: "SFO",
        lat: "37.6148",
        lon: "-122.392",
        name: "San Francisco International Airport",
        city: "San Francisco",
        state: "California",
        country: "United States",
        woeid: "12521721",
        tz: "America/Los_Angeles",
        phone: "(650) 821-8211",
        type: "Airports",
        email: "",
        url: "http://www.flysfo.com",
        runway_length: "11870",
        elev: "12",
        icao: "KSFO",
        direct_flights: "147",
        carriers: "76",
    },
];
